name: Smart Share APK Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Kodni yuklab olish
      uses: actions/checkout@v4

    - name: 2. Java 17 o'rnatish
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 3. Gradle dvigatelini sozlash
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.10' # Repozitoriyada wrapper yo'qligi uchun avtomatik o'rnatiladi

    - name: 4. Loyiha muhitini tayyorlash
      run: |
        # settings.gradle.kts qayerdaligini aniqlab olamiz (oson-share papkasi)
        TARGET_DIR=$(dirname $(find . -name "settings.gradle.kts" -type f | head -n 1))
        echo "Loyiha papkasi: $TARGET_DIR"
        echo "TARGET_DIR=$TARGET_DIR" >> $GITHUB_ENV
        
        cd $TARGET_DIR
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        
        # Yetishmayotgan debug.keystore faylini avtomatik yaratamiz
        keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    - name: 5. Dasturni yig'ish (Build APK)
      run: |
        cd ${{ env.TARGET_DIR }}
        gradle assembleDebug -x test --no-daemon

    - name: 6. Tayyor APK faylni yuklab olish uchun taqdim etish
      uses: actions/upload-artifact@v4
      with:
        name: Smart-Share-Native-APK
        path: "**/app/build/outputs/apk/debug/*.apk"
